project/maps/views.py
import re
import os
from flask import Flask,redirect,render_template,request,url_for,flash,Blueprint,jsonify
from project import session,db
from project.helpers import *
from werkzeug.utils import secure_filename
maps_blueprint=Blueprint(
    'maps',
    __name__,
    template_folder='templates'
)

UPLOAD_FOLDER = './project/static/uploaded/images/'
ALLOWED_EXTENSIONS = set(['jpg'])

@maps_blueprint.route("/", methods=["GET", "POST"])
@login_required
def index():
    error = None
    if request.method == "POST":
        if 'file' not in request.files:
            error='No file part'
        file = request.files['file']
        if file.filename == '':
            error='No selected file'
        if file and allowed_file(file.filename):
            lat=float(request.form.get("sirina"))
            longi=float(request.form.get("duzina"))
            if toclose(lat,longi) == 1:
                result = db.execute("INSERT INTO markers (user, latitude,longitude) VALUES (:user,:lat,:longi)", user=session["user_id"],lat=lat,longi=longi)
                ispisfile=str(result)+".jpg"
                file.save(os.path.join(UPLOAD_FOLDER ,ispisfile))
            else:
                error="marker is too close"
        else:
            error="The file format must be .jpg"
        return render_template("index.html",error=error)
    else:
        return render_template("index.html",error=error)

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@maps_blueprint.route("/update")
def update():
    """Find up to 10 places within view."""

    # ensure parameters are present
    if not request.args.get("sw"):
        raise RuntimeError("missing sw")
    if not request.args.get("ne"):
        raise RuntimeError("missing ne")

    # ensure parameters are in lat,lng format
    if not re.search(r"^-?\d+(?:\.\d+)?,-?\d+(?:\.\d+)?$", request.args.get("sw")):
        raise RuntimeError("invalid sw")
    if not re.search(r"^-?\d+(?:\.\d+)?,-?\d+(?:\.\d+)?$", request.args.get("ne")):
        raise RuntimeError("invalid ne")

    # explode southwest corner into two variables
    (sw_lat, sw_lng) = [float(s) for s in request.args.get("sw").split(",")]

    # explode northeast corner into two variables
    (ne_lat, ne_lng) = [float(s) for s in request.args.get("ne").split(",")]

    # find 10 cities within view, pseudorandomly chosen if more within view
    if (sw_lng <= ne_lng):

        # doesn't cross the antimeridian
        rows = db.execute("""SELECT * FROM markers
            WHERE :sw_lat <= latitude AND latitude <= :ne_lat AND (:sw_lng <= longitude AND longitude <= :ne_lng) 
             LIMIT 10""",
            sw_lat=sw_lat, ne_lat=ne_lat, sw_lng=sw_lng, ne_lng=ne_lng)

    else:

        # crosses the antimeridian
        rows = db.execute("""SELECT * FROM markers
            WHERE :sw_lat <= latitude AND latitude <= :ne_lat AND (:sw_lng <= longitude OR longitude <= :ne_lng) 
             LIMIT 10""",
            sw_lat=sw_lat, ne_lat=ne_lat, sw_lng=sw_lng, ne_lng=ne_lng)

    # output places as JSON
    return jsonify(rows)

def toclose(latids,longit):
    rows = db.execute("""SELECT * FROM markers
            WHERE latitude > :latdmin AND  latitude < :latdmax AND  longitude > :longitmin AND longitude < :longitmax
            """,
            latdmin=latids-0.01,latdmax=latids+0.01, longitmin=longit-0.01,longitmax=longit+0.01)
    if len(rows) < 1:
        return 1
    else:
        return 0

project/users/views.py
import random,os,re
from flask import redirect,render_template,request,url_for,flash,Blueprint
from project import session,db
from werkzeug.security import generate_password_hash,check_password_hash
from project.helpers import *
from werkzeug.utils import secure_filename

users_blueprint=Blueprint(
    'users',
    __name__,
    template_folder='templates'
)

UPLOAD_FOLDER = './project/static/avatars/'
ALLOWED_EXTENSIONS = set(['jpg','png','jpeg'])

@users_blueprint.route("/account", methods=["GET", "POST"])
@login_required
def account():
    error=None
    if request.method == "POST":
        rows = db.execute("SELECT * FROM users WHERE id = :id", id=session["user_id"])
        name=request.form.get("username")
        email=request.form.get("email")
        passw=request.form.get("pass")
        newpassw=request.form.get("newpass")
        suc1=0
        suc2=0
        suc3=0
        suc4=0
        if name and name != rows[0]['username']:
            if len(name) < 5:
                return loadpage(error="Username is too short!")
            suc1=1

        if email and email != rows[0]['email']:
            if len(email) < 5:
                return loadpage(error="Email is too short!") 
            suc2=1           

        if passw:
            if not check_password_hash( rows[0]["password"],passw):
                return loadpage(error="You entered the wrong password!")
            if newpassw:
                if len(newpassw)<8:
                    return loadpage(error="Password is too short!")
                suc3=1
        file=""
        if 'file' in request.files:
            file = request.files['file']
            if file.filename != '':
                if file and allowed_file(file.filename):
                    suc4=1
                else:
                    return loadpage(error="Image format is not supported!")
        
        if suc1==1:
            update = db.execute("UPDATE users SET username=:username WHERE id = :id", username=name,id=session["user_id"])
            if not update:
                return loadpage(error="Username is already taken!")
        if suc2==1:
            update = db.execute("UPDATE users SET email=:email WHERE id = :id", email=email,id=session["user_id"])
            if not update:
                return loadpage(error="Email is already taken!")
        if suc3==1: 
            hash=generate_password_hash(newpassw)
            update = db.execute("UPDATE users SET password=:passw WHERE id = :id", passw=hash,id=session["user_id"])
        if suc4==1:
            extenzija=file.filename.rsplit('.', 1)[1].lower()
            id=session["user_id"]

            rows = db.execute("SELECT * FROM users WHERE id = :id", id=session["user_id"])
            preavat=rows[0]['avatar']
            inc=0
            if preavat[0]=='d' and preavat[1]=='e'and preavat[2]=='f':
                inc=1
            else:

                preavat=preavat.replace('-','.')
                preavat=preavat.split('.')

                if len(preavat)==3:
                    inc=int(preavat[1])
                    inc=inc+1
                else:
                    inc=1
            ispisfile=str(id)+"-"+str(inc)+"."+extenzija
            file.save(os.path.join(UPLOAD_FOLDER ,ispisfile))


            update = db.execute("UPDATE users SET avatar=:avet WHERE id = :id", avet=ispisfile,id=session["user_id"])
 
        return loadpage(error="Changes saved successfully!")
    else:
        return loadpage(error)
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def loadpage(error):
    rows = db.execute("SELECT * FROM users WHERE id = :id", id=session["user_id"])
    return render_template("profile.html",avatar=rows[0]['avatar'],\
        name=rows[0]['username'],email=rows[0]['email'],error=error)
@users_blueprint.route("/logout")
@login_required
def logout():
    session.clear()
    return redirect(url_for("users.login"))

@users_blueprint.route("/login", methods=["GET", "POST"])
@logged
def login():
    error = None
    if request.method == "POST":
        if not request.form.get("name"):
            error = 'insert username'
        if not request.form.get("pass"):
            if error== None:
                error = 'insert password'
            else:
                 error += ' and password'
        if error==None:
            name=request.form.get("name")
            sifra=request.form.get("pass")
            rows = db.execute("SELECT * FROM users WHERE username = :username", username=name)

            if len(rows) != 1 or not check_password_hash( rows[0]["password"],sifra): 
                error = "wrong password or username"

            if error==None:
                session["user_id"] = rows[0]["id"]
                return redirect(url_for("maps.index"))
            else:
                return render_template("login.html",error=error)
        else:
            return render_template("login.html",error=error)
    else:
        return render_template("login.html",error=error)

@users_blueprint.route("/register", methods=["GET", "POST"])
@logged
def register():
    error=None
    if request.method == "POST":
        if not request.form.get("name"):
            error="insert username"
        if not request.form.get("pass"):
            if error!=None:
                error+=" password"
            else:
                error="insert password"
        if not request.form.get("adresa"):
            if error!=None:
                error+=" and email"
            else:
                error="insert email"
        if error==None:
            if len(request.form.get("name"))<5:
                error="username is too short"
            if len(request.form.get("pass"))<8:
                if error==None:
                    error="password is too short"
            if len(request.form.get("adresa"))<5:
                if error==None:
                    error="email is too short"
        if error==None:
            name=request.form.get("name")
            email=request.form.get("adresa")
            hash=generate_password_hash(request.form.get("pass"))
            locat="def"+str(random.randint(1, 9))+".jpg"
            result = db.execute("INSERT INTO users (username, password,email,avatar) VALUES (:username,:hash,:email,:av)", username=name,hash=hash,email=email,av=locat)

            if not result:
                error="username taken"
            if error==None:
                session["user_id"] = result
                return redirect(url_for("maps.index"))
            else:
                return render_template("register.html",error=error)
        else:
            return render_template("register.html",error=error)
    else:
        return render_template("register.html",error=error)

project/templates/layout.html
<html>
    <head>
        <title>Traffic Map</title>
        <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <!-- https://developers.google.com/maps/documentation/javascript/ -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBAhFnVBbRqiFw5MlAd45HHbTjVvGGq0Nc&v=3.exp"></script>


    <!-- https://github.com/corejavascript/typeahead.js/blob/master/doc/jquery_typeahead.md -->
    <script src="https://cdn.rawgit.com/corejavascript/typeahead.js/master/dist/typeahead.jquery.js"></script>

       <!-- http://handlebarsjs.com/ -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    {{ JSGlue.include() }}
    </head>
    <body>
          

            <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #6c4b78;">
                    <a class="navbar-brand" href="{{ url_for('maps.index') }}">Traffic Markers</a>

                    
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                          </button>
              
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('marks.lists') }}">Markers </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('users.account') }}">Profile </a>
                                </li>
                                <li class="nav-item">
                                        <a class="nav-link" href="{{ url_for('users.logout') }}">Log out </a>
                                </li>
                            </ul>
                    </div>
                  </nav>
                  <main>

                        {% block main %}{% endblock %}
                        
                </main>
    </body>
</html>