project/users/views.py
import random,os,re
from flask import redirect,render_template,request,url_for,flash,Blueprint
from project import session,db
from werkzeug.security import generate_password_hash,check_password_hash
from project.helpers import *
from werkzeug.utils import secure_filename

users_blueprint=Blueprint(
    'users',
    __name__,
    template_folder='templates'
)

UPLOAD_FOLDER = './project/static/avatars/'
ALLOWED_EXTENSIONS = set(['jpg','png','jpeg'])

@users_blueprint.route("/account", methods=["GET", "POST"])
@login_required
def account():
    error=None
    if request.method == "POST":
        rows = db.execute("SELECT * FROM users WHERE id = :id", id=session["user_id"])
        name=request.form.get("username")
        email=request.form.get("email")
        passw=request.form.get("pass")
        newpassw=request.form.get("newpass")
        suc1=0
        suc2=0
        suc3=0
        suc4=0
        if name and name != rows[0]['username']:
            if len(name) < 5:
                return loadpage(error="Username is too short!")
            suc1=1

        if email and email != rows[0]['email']:
            if len(email) < 5:
                return loadpage(error="Email is too short!") 
            suc2=1           

        if passw:
            if not check_password_hash( rows[0]["password"],passw):
                return loadpage(error="You entered the wrong password!")
            if newpassw:
                if len(newpassw)<8:
                    return loadpage(error="Password is too short!")
                suc3=1
        file=""
        if 'file' in request.files:
            file = request.files['file']
            if file.filename != '':
                if file and allowed_file(file.filename):
                    suc4=1
                else:
                    return loadpage(error="Image format is not supported!")
        
        if suc1==1:
            update = db.execute("UPDATE users SET username=:username WHERE id = :id", username=name,id=session["user_id"])
            if not update:
                return loadpage(error="Username is already taken!")
        if suc2==1:
            update = db.execute("UPDATE users SET email=:email WHERE id = :id", email=email,id=session["user_id"])
            if not update:
                return loadpage(error="Email is already taken!")
        if suc3==1: 
            hash=generate_password_hash(newpassw)
            update = db.execute("UPDATE users SET password=:passw WHERE id = :id", passw=hash,id=session["user_id"])
        if suc4==1:
            extenzija=file.filename.rsplit('.', 1)[1].lower()
            id=session["user_id"]

            rows = db.execute("SELECT * FROM users WHERE id = :id", id=session["user_id"])
            preavat=rows[0]['avatar']
            inc=0
            if preavat[0]=='d' and preavat[1]=='e'and preavat[2]=='f':
                inc=1
            else:

                preavat=preavat.replace('-','.')
                preavat=preavat.split('.')

                if len(preavat)==3:
                    inc=int(preavat[1])
                    inc=inc+1
                else:
                    inc=1
            ispisfile=str(id)+"-"+str(inc)+"."+extenzija
            file.save(os.path.join(UPLOAD_FOLDER ,ispisfile))


            update = db.execute("UPDATE users SET avatar=:avet WHERE id = :id", avet=ispisfile,id=session["user_id"])
 
        return loadpage(error="Changes saved successfully!")
    else:
        return loadpage(error)
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def loadpage(error):
    rows = db.execute("SELECT * FROM users WHERE id = :id", id=session["user_id"])
    return render_template("profile.html",avatar=rows[0]['avatar'],\
        name=rows[0]['username'],email=rows[0]['email'],error=error)
@users_blueprint.route("/logout")
@login_required
def logout():
    session.clear()
    return redirect(url_for("users.login"))

@users_blueprint.route("/login", methods=["GET", "POST"])
@logged
def login():
    error = None
    if request.method == "POST":
        if not request.form.get("name"):
            error = 'insert username'
        if not request.form.get("pass"):
            if error== None:
                error = 'insert password'
            else:
                 error += ' and password'
        if error==None:
            name=request.form.get("name")
            sifra=request.form.get("pass")
            rows = db.execute("SELECT * FROM users WHERE username = :username", username=name)

            if len(rows) != 1 or not check_password_hash( rows[0]["password"],sifra): 
                error = "wrong password or username"

            if error==None:
                session["user_id"] = rows[0]["id"]
                return redirect(url_for("maps.index"))
            else:
                return render_template("login.html",error=error)
        else:
            return render_template("login.html",error=error)
    else:
        return render_template("login.html",error=error)

@users_blueprint.route("/register", methods=["GET", "POST"])
@logged
def register():
    error=None
    if request.method == "POST":
        if not request.form.get("name"):
            error="insert username"
        if not request.form.get("pass"):
            if error!=None:
                error+=" password"
            else:
                error="insert password"
        if not request.form.get("adresa"):
            if error!=None:
                error+=" and email"
            else:
                error="insert email"
        if error==None:
            if len(request.form.get("name"))<5:
                error="username is too short"
            if len(request.form.get("pass"))<8:
                if error==None:
                    error="password is too short"
            if len(request.form.get("adresa"))<5:
                if error==None:
                    error="email is too short"
        if error==None:
            name=request.form.get("name")
            email=request.form.get("adresa")
            hash=generate_password_hash(request.form.get("pass"))
            locat="def"+str(random.randint(1, 9))+".jpg"
            result = db.execute("INSERT INTO users (username, password,email,avatar) VALUES (:username,:hash,:email,:av)", username=name,hash=hash,email=email,av=locat)

            if not result:
                error="username taken"
            if error==None:
                session["user_id"] = result
                return redirect(url_for("maps.index"))
            else:
                return render_template("register.html",error=error)
        else:
            return render_template("register.html",error=error)
    else:
        return render_template("register.html",error=error)

project/users/templates/login.html
{% extends "prijavljivanje.html" %}

{% block title %}
    Login
{% endblock %}

{% block main %}

    <div class="login-page">
        <div class="form">
            <form class="login-form" action="{{ url_for('users.login') }}" method="post">
                <input type="text" name="name" placeholder="username"/>
                <input type="password" name="pass" placeholder="password"/>
                <button>login</button>
                <p class="message">Not registered? <a href="{{ url_for('users.register') }}">Create an account</a></p>
            </form>


        </div>
        {% if error != none %}
        <div class="alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
                {{error}}
              </div>
        {% endif %}
      </div>
{% endblock %}

project/users/templates/prijavljivanje.html
<html>
    <head>
        <meta charset="utf-8"/>
        <meta content="initial-scale=1, width=device-width" name="viewport"/>
        <link href="{{ url_for('static', filename='login.css') }}" rel="stylesheet"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>
    <body>
        <script>
                $('.message a').click(function(){
                    $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
                 });
        </script>
        <main>

                {% block main %}{% endblock %}
                
        </main>
    </body>
</html>

project/users/templates/profile.html
{% extends "layout.html" %}

{% block title %}
    Login
{% endblock %}

{% block main %}
<link href="{{ url_for('static', filename='profile.css') }}" rel="stylesheet" type="text/css"/>
<div class="container" style="padding-top: 60px; margin:0 auto 5px;">
    <form class="change-form" action="{{ url_for('users.account') }}" method="post" enctype="multipart/form-data">
    <div class="row">
      <!-- left column -->
      <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="text-center">
                <img src="static/avatars/{{avatar}}" class="avatar rounded-circle img-thumbnail" alt="avatar">
            <label for="uploader" class="kamera">
                    <img src="static/images/camera2.png" class="taster">
                <input type="file" name="file" id="uploader"  style="display:none">
            </label>
        </div>
      </div>
      <!-- edit form column -->
      <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
        {% if error != none %}
        <div class="alert alert-info alert-dismissable">
          <a class="panel-close close" data-dismiss="alert">×</a> 
          <i class="fa fa-coffee"></i>
          {{error}}
        </div>
        {% endif %}
        <h3>Personal info</h3>
          <div class="form-group">
            <label class="col-md-3 control-label">Username:</label>
            <div class="col-md-8">
              <input class="form-control" name="username" value="{{name}}" type="text">
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-3 control-label">Email:</label>
            <div class="col-md-8">
              <input class="form-control" name="email" value="{{email}}" type="email">
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-3 control-label">Password:</label>
            <div class="col-md-8">
              <input class="form-control" name="pass" value="" type="password">
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-3 control-label">New password:</label>
            <div class="col-md-8">
              <input class="form-control" name="newpass" value="" type="password">
            </div>
          </div>
          <div class="form-group">
            <label class="col-md-3 control-label"></label>
            <div class="col-md-8">
              <button type="submit" class="btn btn-primary">Save Changes</button>
              <span></span>
            </div>
          </div>
        
      </div>
    </div>
  </form>
  </div>
  <script>
        $(function(){
            $('#uploader').change(function(){
              var input = this;
              var url = $(this).val();
              var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
              if (input.files && input.files[0]&& ( ext == "png" || ext == "jpeg" || ext == "jpg")) 
               {
                  var reader = new FileReader();
          
                  reader.onload = function (e) {
                     $('.avatar').attr('src', e.target.result);
                  }
                 reader.readAsDataURL(input.files[0]);
              }
              else
              {
                $('.avatar').attr('src', 'static/avatars/{{avatar}}');
              }
            });
          
          });
  </script>
{% endblock %}

project/users/templates/register.html
{% extends "prijavljivanje.html" %}

{% block title %}
    Registracija
{% endblock %}

{% block main %}
    <div class="login-page">
        <div class="form">
            <form class="register-form" action="{{ url_for('users.register') }}" method="post">
                <input type="text" placeholder="name" name="name"/>
                <input type="password" placeholder="password" name="pass"/>
                <input name="adresa" type="email" placeholder="email address" />
                <button>create</button>
                <p class="message">Already registered? <a href="{{ url_for('users.login') }}">Sign In</a></p>
            </form>
        </div>
        {% if error != none %}
        <div class="alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
                {{error}}
              </div>
        {% endif %}
      </div>
{% endblock %}