project/marks/views.py
import re
import os
from flask import Flask,redirect,render_template,request,url_for,flash,Blueprint,jsonify
from project import session,db
from project.helpers import *
from werkzeug.utils import secure_filename

markers_blueprint=Blueprint(
    'marks',
    __name__,
    template_folder='templates'
)

UPLOAD_FOLDER = './project/static/uploaded/images/'

@markers_blueprint.route("/lists")
@login_required
def lists():
    return showlist()

def showlist():
    rows = db.execute("SELECT * FROM markers")
    for x in range(0, len(rows)):
        names = db.execute("SELECT username FROM users where id=:id",id=rows[x]['user'])
        rows[x]['user']=names[0]['username']
    return render_template("lists.html",data=rows)
@markers_blueprint.route('/lists/<page_id>', methods=["GET", "POST"])
@login_required
def listid(page_id):
    marker = page_id
    table = db.execute("SELECT * FROM markers WHERE id=:id", id=int(marker))
    if len(table)==0:
        return redirect(url_for("marks.lists"))
    if request.method == "POST":
        if request.form.get("text_name"):
            hajde=str(request.form["text_name"])
            result = db.execute("INSERT INTO commets (user, marker,text) VALUES (:username,:marker, :ipsisi )", username=session["user_id"],marker=marker,ipsisi=hajde)
            return showpage(marker)
        elif request.form.get("prodId"):
            result = db.execute("DELETE FROM commets WHERE id=:id", id=int(request.form.get("prodId")))
            return showpage(marker)
        elif request.form.get("all"):
            result = db.execute("DELETE FROM commets WHERE marker=:id", id=int(marker))
            table = db.execute("DELETE FROM markers WHERE id=:id", id=int(marker))
            ispisfile=str(marker)+".jpg"
            os.remove(os.path.join(UPLOAD_FOLDER, ispisfile))
            return redirect(url_for("marks.lists"))
        else:
            return redirect(url_for("marks.lists"))
    else:
        return showpage(marker)

def showpage(marker):
    rows = db.execute("SELECT * FROM markers WHERE id=:id",id=marker)
    names = db.execute("SELECT * FROM users WHERE id=:per",per=int(rows[0]['user']))
    user = db.execute("SELECT * FROM users WHERE id=:per",per=session["user_id"])
    pozicija=str(rows[0]['latitude'])+" "+str(rows[0]['longitude'])
    vreme=str(rows[0]['time'])+" "+str(rows[0]['date'])
    return render_template("listsbyid.html",image=marker,person=names[0]['avatar']\
    ,name=names[0]['username'],lat=pozicija,time=vreme,data=Comments(marker),user=user)

def Comments(marker):
    comm = db.execute("SELECT * FROM commets WHERE marker=:per",per=marker)
    for x in range(0, len(comm)):
        names = db.execute("SELECT username,avatar FROM users where id=:id",id=comm[x]['user'])
        comm[x]['user']=names[0]['username']
        comm[x]['avatar']=names[0]['avatar']
    return comm

project/marks/templates/lists.html
{% extends "layout.html" %}

{% block title %}
    Lists
{% endblock %}

{% block main %}
<link href="{{ url_for('static', filename='lists.css') }}" rel="stylesheet"/>

<link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
<div class='container'>
    {% for dt in data %}
    <a class="nav-link" href="{{ url_for('marks.listid',page_id=dt.id) }}">
    <div class='list-card'>
        <img alt='' src="static/uploaded/images/{{dt.id}}.jpg">
        <div class='list-details'>
          <div class='list-name'>posted by: {{dt.user}}</div>
          <div class='list-location'>{{dt.latitude}} {{dt.longitude}}</div>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</link>

{% endblock %}

project/marks/templates/listsbyid.html
{% extends "layout.html" %}

{% block title %}
    Lists By Id
{% endblock %}

{% block main %}
<link href="{{ url_for('static', filename='listsbyid.css') }}" rel="stylesheet"/>
<div class="container">
    <div class="card hovercard">
       <img src="../static/uploaded/images/{{image}}.jpg" alt=""/>
       <div class="avatar">
          <img src="../static/avatars/{{person}}" class="img-thumbnail" alt="" />
       </div>
       <div class="info">
          <div class="title">
             user: {{name}}
             {% if user[0].username == name %}
             <form action="{{ url_for('marks.listid',page_id=image) }}" style="margin:0px; display:inline-block;" method="post">
                    <input id="prodId" name="all" type="hidden"  value="{{image}}">
                  <button id="deletebtn" type="submit" class="btn btn-danger">Delete</button>
                  </form>
            {% endif %}
            <br>
             position: {{lat}}<br>
             time: {{time}}
          </div>
       </div>

    </div>
    </div>
    

    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <div class='container'>
        {% for dt in data %}
        <div class='list-card'>
            <img alt='' src="../static/avatars/{{dt.avatar}}" class="rounded-circle img-thumbnail">
            <div class='list-details'>
              <div class='list-name' style="display:inline-block;">{{dt.user}}</div>
              {% if user[0].username == dt.user %}
              <form action="{{ url_for('marks.listid',page_id=image) }}" style="display:inline-block;" method="post">
                <input id="prodId" name="prodId" type="hidden"  value="{{dt.id}}">
              <button id="deletebtn" type="submit" class="btn btn-danger">Delete</button>
              </form>
              {% endif %}
              <div class='list-location'>{{dt.text}}</div>
            </div>
          </div>
        {% endfor %}
        <div class='list-card'>
            <img alt='' src="../static/avatars/{{user[0].avatar}}" class="rounded-circle img-thumbnail">
            <div class='list-details'>
              <div class='list-name'>{{user[0].username}}</div>
              <form action="{{ url_for('marks.listid',page_id=image) }}" method="post">
              <textarea placeholder="comment.." class="list-location form-control" rows="2" cols="50" id="text" name="text_name" style="resize: none; margin:2px;"></textarea>
              <button type="submit" id="dodaj" class="btn btn-success">Post</button>
                </form>
            </div>
          </div>
      </div>
    </link>
    
{% endblock %}